SWEET-DEVELOPERS/sweet-client

.github/workflows/deploy.yml, .github/workflows/preview.yml
- close #1 
- Github Actions는 작업 흐름(workflow)을 자동화해주는 툴이라고 생각하면 좋을 것 같아요.
- 총 2개의 workflow를 만들었습니다.
-  `preview`는 `main`, `develop`으로 머지하는 PR을 올릴 경우 임시 배포 후 배포 화면을 미리 볼 수 있도록 하는 파일
-  `deploy`는 `main`으로 푸시가 이루어지면 자동 배포가 이루어지도록 하는 파일
- `concurrency` 설정으로 동시성을 정해주는 이유는 여러 PR이 동시에 들어온 경우에 여러 PR에 대한 빌드 및 테스트 작업이 동시에 실행되면서 충돌이 생길 수 있기 때문입니다.
```yaml
concurrency: preview-${{ github.ref }}
```
- 이외의 설정들에 대한 설명은 모두 주석으로 추가했습니다!
‼️ 각자 VSC에서 Github Actions 익스텐션을 설치해주세요!
[Automating and deploying workflows with GitHub Actions](https://resources.github.com/learn/pathways/automation/essentials/automating-deploying-workflows-with-github-actions/)
=> [초기세팅] GitHub Actions 설정

src/main.tsx, src/style/index.tsx, src/style/mixin.ts, src/style/theme.ts
- close #22  
mixin.ts를 아래와 같이 설정해두었습니다.
```typescript
interface MixinProps {
direction: string;
align: string;
justify: string;
}
const mixin = {
// flex
flexBox: ({ direction = 'row', align, justify }: MixinProps) => css`
display: flex;
flex-direction: ${direction};
align-items: ${align};
justify-content: ${justify};
`,
inlineFlexBox: ({ direction = 'row', align, justify }: MixinProps) => css`
display: inline-flex;
flex-direction: ${direction};
align-items: ${align};
justify-content: ${justify};
`,
flexCenter: ({ direction = 'column' }: MixinProps) => css`
display: flex;
flex-direction: ${direction};
align-items: center;
justify-content: center;
`,
};
export default mixin;
```
그 후 theme.ts에서
```typescript
import mixin from './mixin';
const theme = { mixin }; …
```
=> [초기세팅] 자주 사용하는 속성들 mixin 설정

src/components/common/Button/Cta/medium/BtnMedium.style.ts, src/components/common/Modal/Modal.style.ts, src/components/common/Modal/Modal.tsx
- close #76 
- 사용법 알려드릴게용! 아래 코드와 같이 <Modal> 사이엔 컴포넌트 텍스트가 들어가면 되고 띄어쓰기 <br/>태그로 분리시킬수 있습니다.
- 함수 같은 경우도 전달하면 버튼 클릭시 잘 동작하는 것을 확인할 수 있었습니다. 다만 함수 전달 로직이이제 컴포넌트에서 함수 생성 -> 공통모달에 전달 -> 공통모달에서 또 공통 버튼에 함수 전달 이여가지고 이게 최선인지는 더 고민해보고 리팩토링 해볼게요! 감사합니다
=> [공통컴포넌트] 모달창 구현

src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.tsx, src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx, src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.style.ts, src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.tsx, src/components/TournamentNew/TournamentResult/TournamentResultCard/TournamentResultCard.tsx
- close #118
- 제가 바로 useState 지옥입니다. 
- 추후 리팩토링으로 아래 레퍼런스 참고해서 🫨 useReducer 사용해볼까 생각 중입니다. 혹은 `Jotai` 써서 관리해보고 싶습니다.
[useState 지옥에서 벗어나기](https://velog.io/@eunbinn/a-cure-for-react-useState-hell)
=> [토너먼트] 다음 버튼 로직 구현 및 이미지 불러오기

src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx, src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamentTitle.tsx, src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamernTitle.style.ts, src/types/tournament/index.d.ts
=> [토너먼트] 리프레쉬 아이콘 작동 및 스타일 수정

src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx, src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.tsx, src/components/TournamentNew/TournamentResult/TournamentResultFooter/TournamentResultFooter.tsx, src/components/TournamentNew/TournamentResult/TournamentResultUser/TournamentResultUser.tsx, src/components/common/Button/Next/BtnNext.tsx
- close #177 
- 다시하기 버튼 같은 경우, room Id 를 url로 받고 있어서 reload처리 즉, 새로고침 처리 됐을 때 한번 테스트 해야 될 것 같습니다. 
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/104339899/3cd2f3d0-1273-4cb9-9435-1d2f5633338a
=> [토너먼트] 다음버튼 활성화, 타이머 세팅, 다시하기 버튼 구현 

src/apis/client.ts, src/components/Login/index.tsx
- close #313 
- 로그인 유지를 위해 accessToken 재발급 받는 경우를 interceptor로 진행하고 있었어요. 그러던 와중, refresh Token 이 만료 되는 경우에 로그인 페이지로 넘어가도록 해두었는데, 이 부분이 status로 구분이 아니라, message로 구분을 해야하더라구요..
명세서 적혀 있지 않아서 ㅠㅠ 확인이 어려웠네요.. 아마 이게 문제이지 않았을까 생각합니다.
일단 배포 페이지에 적용하고 추후 코드 리뷰 받을게요 !! pr 한번에 올리도록 하겠습니다 🔥
https://mingmeng030.tistory.com/264
=> [리프레쉬 토큰] 리프레쉬 토큰 만료 시 재로그인

src/pages/Participants/ParticipantsView.tsx
useEffect로 isToken을 boolean으로 주고 그에 따른 삼항 연산자로 뷰를 보여주는 로직으로 수정하였습니다.
- close #380 
기존에는 localStorage get Item으로 토큰을 들고와 토큰 여부에 따라 다른 뷰를 보여주는 방식으로 구현했었는데요.
이렇게 구현하니 로그인이 되지 않은 사용자가 진입했을 시 모바일에서 카카오 로그인이 보이지 않는 현상이 있습니다. 
따라서 useEffect로 isToken을 boolean으로 판별 후, true일 때와 false일 때로 구분하여 뷰를 보여주는 방식으로 일부 수정하였습니다. 
현재 이 부분을 로컬에서 확인할 수 있는 방법이 없어서, 확인을 위한 머지가 한 번 필요할 것 같습니다. (제발 되라... ㅠ)
yarn dev --host 에서는 모바일에서 화면 진입 시 아래와 같은 화면이 발생하고 있어 확인이 어렵습니다.
이와는 다른 방식으로 localhost 5173은 모바일로 들어갈  수 없으니 확인이 힘들기에 배포 페이지에 한 번 적용시켜 봐야 할 것 같습니다!! 
현재까지 확인된 바로는, 웹에서는 잘 작동하고 있습니다!! 지금은 너무 늦었으니 이따 여러분들 일어나시면 그 때 머지 후 모바일로 확인하고 바로 이 부분 다시 작업 들어가겠습니다.
=> feat: 모바일에서 카카오 로그인 버튼 안보이는 현상 로직 수정

src/pages/Participants/ParticipantsView.tsx
=> [온보딩] isToken 값 기본으로 false 설정을 제거하여 확인

src/components/Tournament/Intro/TournamentDeleteButton/TournamentDeleteButton.tsx, src/components/Tournament/Intro/TournamentIntroContainer.tsx
- close #373 
- 토너먼트 중복 참여자일 경우 모달창을 띄웠습니다. 
- 그리고 현재 any 및 string 값으러 에러 판별에 대해서 타입 해결을 하다가 시간이 길어져서 이슈 따로 파겠습니다! 간단히 봐주시면 될 것 같습니다 :) 
>다만 궁금한건,,이제 모달창을 띄우면 그냥 있는 화면 즉, 컴포넌트 위에 모달창을 띄우고 싶은데 지금 return을 해줘야 해서 return으로 state값을 바꾸려했는데 잘 되지 않았습니다 흑흑..! 그래서 그냥 흰화면에 모달창만 뜨고 다시 돌아오는데 좋은 방법이 있을까요? 
- 선물이 0개일 때 선물방 종료하기 버튼 기능 구현했습니다.
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/104339899/a0544317-62d0-48b1-959e-fbc456981292
=> [1.5차 QA : 토너먼트] 토너먼트 방 종료 버튼 구현 및 중복 참여자 ui 개선

src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx, src/components/GiftHome/GiftHome2030Gifts/GiftHome2030Gifts.tsx, src/components/GiftHome/GiftHomeFriendsGifts/GiftHomeFriendsGifts.tsx, src/components/GiftHome/GiftHomeMyGifts/GiftHomeMyGiftsItem.style.ts, src/components/GiftHome/common/GiftHomeShowcase.styled.ts, src/components/GiftHome/common/GiftHomeShowcaseItem.styled.ts, src/components/common/Modal/DeleteModal.style.ts, src/components/common/Modal/DeleteModal.tsx, src/pages/GiftHome/GiftHomeMyGifts/GiftHomeMyGifts.style.ts, src/pages/GiftHomeDetail/GiftHomeDetail.tsx
- close #398
- 자잘한 스타일 수정들이라 변경사항 간단하게 확인해주시면 될 것 같습니다:)
- 실수로 해당 PR에서 선물등록 삭제 모달 추가를 구현했습니다..! 기디 요청에 맞게 선물 삭제 버튼을 누르면 재확인하는 모달을 띄워주었고, 이에 따라 DELETE가 삭제 확인 버튼을 눌렀을 때 작동하도록 수정했습니다.
- 엠티뷰 중앙 정렬
- 2030 글자 안 잘리게 수정
- 선물방 메인 아이템 정렬
- 삭제모달 구현(다만 X 아이콘 색상 변경 계속 안 되고 있어서 이 부분은 이따가 다른 모달 추가 구현 시 함께 해결하겠습니다)
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/92876819/1c297185-78c1-4fd3-89d8-d8003d010d69
=> [1.5차 QA] 선물홈 스타일 QA 반영, 선물등록 모달창 추가

src/assets/svg/IcDown.tsx, src/components/Footer/Footer.tsx, src/pages/LoginError/LoginError.style.ts, src/pages/Start/LogoHeader/LogoHeader.style.ts, src/pages/Start/Start.style.ts, src/pages/Start/Start.tsx, src/pages/Start/StartAnimation/DownIconAnimation/StartDownIconAnimation.style.ts, src/pages/Start/StartAnimation/DownIconAnimation/StartDownIconAnimation.tsx, src/pages/Start/StartAnimation/GiftAnimation/StartGiftAnimation.style.ts
- close #432 
- 화살표 밑으로 스크롤 시 없어지게 하는걸 원래 기존에 만들어둔 애니메이션 컴포넌트가 아닌 다른 코드를 작성해 수정했어요 !!! 훨씬 자연스러워 졌답니다 !! 기존엔 스크롤에 반응하는 애니메이션이 아니고, viewPort 에 반응하는 애니메이션이었어서 가만히만 있어도 화살표가 없어졌거든요. 적용된 화면은 영상을 참고해주시고, 코드는 변경파일을 확인해주세요 !!
- 원래 토너먼트 애니메이션이 안 보여서 직접 구현 하려고 했는데, 지금은 잘 보이더군요.. 배포 페이지에서 또 안 보이면, 로티 그냥 다 삭제해버리고 직접 구현해야할거 같아요 !!
- 나머지는 다 margin 이나 padding 입니다 !! 코드는 변경사항 확인 적용 화면은 영상 확인 해주세요 !
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/38005874/c626b7f3-ae0e-41ae-8bd5-75ea644702d9
=> [시작페이지] 2차 qa 내용 반영입니다 !

src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx, src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx, src/components/common/Modal/DeleteModal.tsx, src/hooks/useCopyClip.tsx, src/pages/GiftHome/GiftHome.tsx, src/style/GlobalStyle.ts
- close # 
- 아직 디쟌쌤 답변을 기다리고 있는 부분들이 있어 임시로 열어만 둡니다!
- 모달을 여닫기 위한 setState를 넘겨주는 것으로 수정했습니다! (다른 방식 제안도 환영입니다)
- 모달 컴포넌트
```typescript
interface DeleteModalProps {
children: React.ReactNode;
onClickDelete: (giftId?: number) => void;
setIsModalOpen: React.Dispatch<React.SetStateAction<boolean>>;
clickedItem?: number | undefined;
}
// 중략
<BtnMedium
customStyle={{
width: '12rem',
outline: 'none',
border: 'none',
backgroundColor: 'white',
color: 'black',
}}
onClick={() => (clickedItem ? onClickDelete(clickedItem) : onClickCancel())}
>
네, 삭제할게요
</BtnMedium>
```
- 사용 예시
```typescript
{isModalOpen && (
<DeleteModal
setIsModalOpen={setIsModalOpen}
onClickDelete={handleClickConfirmDeleteBtn}
clickedItem={clickedItem}
>
정말 상품을 삭제하시겠어요?
</DeleteModal>
)}
```
=> 공토 컴포넌트 공유를 위한 임시 PR입니다

src/components/Tournament/Intro/TournamentIntroContainer.tsx, src/components/Tournament/TournamentFlow/TournamentCard/TournamentCard.style.ts, src/components/Tournament/TournamentRanking/TournamentRanking.tsx, src/components/Tournament/TournamentRanking/TournamentRankingCard/TournamentRankingCard.style.ts, src/components/Tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.style.ts
- close #419 
- 간단한 스타일 사항들 수정했습니다~ 말 줄임표 이제 마스터 한 것 같네요 ㅎㅎ!
[말줄임표 마스터하기 참고 레퍼런스](https://velog.io/@april_5/CSS-ellipsis-%EB%A7%90%EC%A4%84%EC%9E%84-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)
=> [토너먼트] 2차 QA 스타일 변경사항

src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx, src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx, src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx, src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx, src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WithoutLinkWriteItemInfo.tsx, src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WriteItemInfo.tsx, src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx, src/components/GiftAdd/AddGiftLink/common/LinkAddHeader/LinkAddHeader.tsx, src/context/AddGift/AddGiftContext.tsx, src/hooks/queries/gift/usePostGift.tsx, src/hooks/useConvertURLtoFile.tsx, src/hooks/useHandleImageUpload.tsx, src/pages/GiftAdd/GiftAddPage.tsx
- close #441 
- case문으로 한 페이지 안에서 여러 컴포넌트들을 갈아 끼우고 있는 형태라서 state 변동에 즉각적인 반응을 주기 위해서는 prop을 모든 페이지들을 관리하는 컴포넌트로 빼주어야 해서 굉장히 많은 props drilling을 겪게 되었습니다. 이번 스프린트 이후에 리팩토링이 많이 이루어져야 할 것 같습니다. context 추가에 대해 고민중입니다.
- 예외처리에 집중했습니다.(링크 유무, 뒤로 갔다가 다시 돌아왔을 때, 이름만 바꿨을 때 등등)
- 오픈그래프로 정보를 가져오는 경우 계속 정보들이 초기화되어 context를 사용했습니다.
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/92876819/e64de033-9feb-49fa-b6e0-6ac190472736
=> [선물 등록] 선물 등록 완료 버튼 활성화 기능 수정

src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx, src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx, src/hooks/useConvertURLtoFile.tsx
- close #464 
- 파일 변환 불가능한 오픈 그래프 이미지 url이 들어오는 경우가 있어 직접 입력 화면 진입 시 이미지 url을 무조건 빈 값으로 초기화해주는 코드를 추가했습니다. 더 좋은 방식으로 초기화가 가능할지 고민해봤는데 현재는 이미지 첨부 컴포넌트를 직접 입력과 링크 입력이 공유하고 있어 useEffect를 사용해 초기화하는 방식으로 수정했습니다. 추후 리팩토링하면서 컴포넌트를 하나 더 만들거나 props 정리를 해봐야 할 것 같아요.
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/92876819/5b11d4ef-0124-406e-bb2c-85c2b8f88642
=> [선물 등록] 이미지 url 파일 변환 실패 시 선물 등록 사항 초기화되도록 수정 

package.json, src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx, src/hooks/useHandleImageUpload.tsx, yarn.lock
- close #488 
- 기존의 이미지 용량 압축 라이브러리는 웹 이미지 형식 기준이라 heic를 input으로 받지 않는 것 같더라고요🥲 하지만 스윗 특성상 핸드폰으로 찍은 사진을 올리는 경우가 많을 것 같아 heic 형식을 변환하는 라이브러리를 적용해서라도 가져가야 할 것 같다고 생각했어요. 다만 이렇게 되면 heic => webp => 압축 이라는 과정으로 늘어나서 heic를 업로드할 때는 시간이 좀 더 걸리는 단점이 생겼어요. 이후에 로딩 뷰를 추가하거나 최적화 가능한 부분은 더 진행해보겠습니다!
=> refactor: heic 변환 처리 추가

src/components/CardRoom/DoneCardRoom.tsx, src/components/CardRoom/EditCardRoom.tsx, src/components/CardRoom/ProgressCardRoom.tsx, src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts, src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx, src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts, src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx, src/pages/MyPage/Detail/EmptyView/EmptyView.style.ts, src/pages/MyPage/Detail/EmptyView/EmptyView.tsx
- close #499
- 선물방이 없을때 버튼 클릭 시 선물방 생성으로 이동하도록 하였습니다.
- 또한 empty view를 공동으로 구성하여 컴포넌트화 시켰습니다.
- 또한 issue 속에 있는 태그 위치를 수정하는 과정이 drop 된줄 알고 확인해 봤는데 로컬에선 잘 예쁘게 변경 되었고, 배포 페이지에서만 이상한걸 보니 아마 main 반영이 안 된거 같습니다 ! 해당 사항 배포페이지에 같이 적용해보도록 하겠습니다.
=> [마이페이지] 선물방으로 이동 버튼 기능 추가

src/components/Tournament/Intro/TournamentDeleteButton/TournamentDeleteButton.tsx, src/components/Tournament/Intro/TournamentIntroContainer.tsx, src/hooks/queries/tournament/useDeleteRoom.tsx
- close #407 
- object%20Object이슈 해결했습니다.onclick 에 룸아이디를 프롭으로 전달안해서 생긴 문제였어요 ㅎㅎ
=> [토너먼트] 강제종료

package.json, src/App.tsx, yarn.lock
- close #510 
- 추후 GA를 적용하면 제거하겠지만, 일단 vercel analytics와 speed-insights를 적용했어요:)
-  아무래도 저희가 계속 최적화에 대해 고민하면서 리팩토링 중이라서, 유저가 더 들어올 것으로 예상되는 오늘 밤 전에 최적화와 관련해 도움을 얻을 수 있을 것 같은 speed-insights도 같이 적용했어요. 다만 lighthouse와 다르게 RUM(Real User Monitoring) 방식이라서 서비스를 사용하는 실제 유저의 활동기록을 기반으로 성능을 측정하기 때문에 사용자 환경에 따라 점수가 달라질 수 있는 특징이 있습니다. 대신 사용자 경험이 어떤지 살펴보기 좋을 것 같아서 같이 적용해보았어요.
[Vercel 사이트](https://vercel.com/docs/speed-insights/quickstart)
=> [공통] vercel analytics, speed-insights 적용

src/App.tsx, src/components/KakaoAd/KakaoAd.tsx, src/components/KakaoAd/KakaoAdCallback.style.ts, src/components/KakaoAd/KakaoAdCallback.tsx, src/pages/MyPage/MyPage.tsx
- close #517 
- useEffect 와 useRef를 활용하여 적용했습니다.
- 해당 부분이 마이페이지가 아닌 메인 화면에 위치 시키지 않은 이유는 디자인을 방해 할 거 같다라는 판단이 들어서 입니다.
- 추후 디자이너와 TL과 상의하여 광고 위치나, 배너 사이즈를 상의해봐도 좋을 거 같습니다.
- kakao ad 가 아닌 다른 광고들도 추후 붙여 나가면 좋을 거 같습니다.
- 해당 부분 이미지는 하단 스크린샷을 참고해주세요!
https://velog.io/@yoonth95/React-kakao-Adfit-%EC%88%98%EC%9D%B5%ED%99%94-%EC%A0%81%EC%9A%A9
https://adfit.kakao.com/dashboard
=> [마이페이지] 하단에 카카오 광고 배너 삽입
