index.html, package.json, src/App.tsx, src/style/GlobalStyle.ts, utils/setScreenSize.ts, yarn.lock
- close #5 
1. GlobalStyle 코드를 작성함에 있어서, 기본적으로 필요할 것 같다고 생각이 드는 속성들만 우선적으로 작성하였습니다.
폰트와 같은 것들은 디자인이 나온 후에 추가하는 방향으로 가야할 것 같습니다!
2. ### 알라딘 합동세미나 조의 코드를 살펴보니, reset을 굉장히 세세하게 잘 설정해주었더라구요. 
**그러나 여러 자료를 찾아보니, styled-reset이라는 라이브러리가 있더군요. 저희도 이 라이브러리를 고려해보는 것은 어떨까요? 많은 피드백 부탁드립니다 ㅎㅎ**
3. 메타태그도 수정하였습니다. 
```html
<html lang="ko">
```
```html
<meta
name="viewport"
content="width=device-width, user-scalable=no, initial-scale=1.0,  
maximum-scale=1.0, minimum-scale=1.0"
/>
```
4. 이어서 setScreenSize 유틸 함수를 지민이가 알려준 레퍼런스를 통하여 작성하였는데, 
블로그에는 App.tsx에 작성하라고 되어있지만, 
이대로 App.tsx에 작성하기엔 뭔가 코드가 깨끗해보이지는 않는듯 하여 utils폴더에 따로 빼서 추상화를 시켜보았습니다.
```javascript
export const setScreenSize = () => {
const vh = window.innerHeight * 0.01;
document.documentElement.style.setProperty("--vh", …
```
=> [초기세팅] GlobalStyle 작성

.commitlintrc.json, .husky/pre-commit, package.json, yarn.lock
- close #10 
- husky 설치 하고 linst-staged도 해놨어요!
- 하나더 봐줬으면 하는 부분은, 아직 commit msg 관련 설정을 안 해놨는데, 이거 도입하는걸 어떻게 생각하는지 의견 궁금해요!! commit convention 관련 부분이어서 husky 자체에서도 설정이 가능하거든요 !! 의견 부탁합니다!
=> 다들 좋다고 하여 지금 commlint 도 설정해뒀어요!!!! 기본적인 단어들만 추가해 놨는데, 리뷰 부탁합니다 ;)
=> [초기세팅] husky 설정 및 lint staged 설정

package.json, src/App.tsx, src/recoil/atoms.ts, yarn.lock
- close #11 
- recoil 폴더 생성했습니다! 폴더 구조는 및에 스크린샷 참고 해주세요.
(폴더 명이 겹치면 충돌 날 수도 있어서 처리 해야할 수도 있을 거 같아요 !! 폴더 구조 세팅 할때 @imeureka )
- 흠 그리고 이 부분 유의해서 봐주세요!! 제가 app.tsx 파일에서 충돌 날거 각오 하고 RecoilRoot태그 생성해뒀어요!! 그래서, app.tsx 파일 다 merge 후 pull 받아오고 충돌 해결 한 후에, merge 해야할 거 같아서 해당 내용도 함께 남겨 봅니다!
=> [초기세팅] recoil 설치 및 파일 설정

package.json, src/App.tsx, src/apis/queryKeys.ts, yarn.lock
- close #12 
- 충돌 날거 각오 하고 app.tsx 내부에 provider로 감싸뒀어요! 이것도 pull 받아와서 충돌 해결 후 merge 하도록 하겠습니다!
- 제가 queryKeys에 대한 고민을 많이 했는데, apis 폴더 내부에 queryKeys 파일을 하나 만들어 두었어요. 저기서 key값 관리를 하는게 어떤가 생각해요. 
예를 들어 user와 관련된 api에서의 react-query key값들을
이런식으로 const user = {} 만들어두고,
apis/user.ts 폴더에서 
이렇게 user.어쩌구 불러와서 react-query를 사용하는거에요!
여기서는 useQuery를 썼네요.
이렇게 다양하게 react-query에서의 기능을 사용할때 key값들을 관리해주는게 필요할 거 같아서 해당 부분을 미리 파일 생성 해두었습니다. 
https://www.zigae.com/react-query-key/
이 자료를 참고한건 아닌데, 비슷한 느낌인거 같아 첨부해요. 더 좋은 레퍼런스가 있다면 공유하도록 하겠습니다!
https://velog.io/@oats7777/%EB%82%A0%EB%A1%9C%EB%A8%B9%EB%8A%94-REACT-QUERY-1%ED%8E%B8
=> [초기세팅] react-query 설치 및 세팅 및 key 파일 생성

README.md
- close #19 
- 저희 깃헙 위키는 작업 더 하면서 계속 업데이트하면 될 것 같고 일단은 채울 수 있는 것만 채워놨습니다!
- 추가하거나 수정하고 싶은 부분은 언제든지 자유롭게 업데이트하고 공유해줘도 좋아요~!
- 리드미에서 수정하면 좋을 부분 피드백 언제든지 환영입니다!:)
- 제 예전 플젝 리드미와 호은님이 공유해준 리드미를 활용했습니다!
- [Co-nect](https://github.com/yulpumta-clone-team/Co-nect)
- [TATTOUR](https://github.com/TEAM-TATTOUR/tattour-client)
=> [리드미] 웹 레포 리드미 작성

src/style/theme.ts
- close #42 
- 개발 시 편의성을 위해 구조를 수정했습니다~!
=> [초기세팅] theme fonts, colors 구조 수정

src/components/common/Button/Change/BtnChange.tsx, src/components/common/Button/Cta/SmallStroke/BtnSmallStroke.tsx, src/components/common/Button/Cta/fill/BtnFill.tsx, src/components/common/Button/Cta/medium/BtnMedium.tsx, src/components/common/Button/Edit/BtnEdti.tsx, src/components/common/Button/Logout/BtnLogout.tsx, src/components/common/Button/Next/BtnNext.tsx, src/components/common/Button/Radio/BtnRadio.tsx, src/components/common/Button/Registration/BtnRegistration.tsx, src/components/common/Button/Subtitle/BtnSubtitle.tsx
- close #60 
figma 상에서 custom을 해야하는 버튼들이 있어서 옵셔널 파라미터로 customStyle 모두 다 추가해두었습니다 !!
=> [공통컴포넌트 ] button customstyle 추가

src/components/TournamentNew/Intro/TournamentContainer.tsx, src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx, src/components/TournamentNew/TournamentResult/TournamentResult.tsx, src/components/TournamentNew/TournamentResult/TournamentResultFooter/TournamentResultFooter.tsx, src/hooks/queries/tournament/useGetItem.tsx, src/hooks/queries/tournament/usePostScore.tsx, src/hooks/tournament/useTournament.tsx, src/pages/TournamentOngoing.tsx, src/types/tournament/index.d.ts
=> [토너먼트] 토너먼트 선물 리스트 조회 API

src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.style.ts, src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx, src/components/TournamentNew/TournamentRanking/TournamentRankingCard/TournamentRankingCard.tsx, src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.style.ts, src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx, src/hooks/queries/tournament/useGetRanking.tsx, src/types/tournament/index.d.ts
=> [토너먼트] 토너먼트 최종 결과 조회 API

src/components/TournamentNew/TournamentRanking/TournamentRanking.style.ts, src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx, src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx, src/hooks/useCopyClip.tsx
- close #139 
- 사용법 알려드릴게용 🥳
링크 복사 될 baseUrl을 입력해줍니다. 
const baseURL = import.meta.env.VITE_APP_BASE_URL;
그리고 사용해주시면 됩니당 위 사진을 참고해주세요
=> [커스텀훅] 링크복사 함수 커스텀 훅 분리 

index.html, src/components/TournamentNew/Intro/TournamentContainer.tsx, src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.style.ts, src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.tsx, src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx, src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx, src/pages/TournamentPage.tsx, src/router/Router.tsx
=> [공통] 폰트 적용 및 토너먼트 타이머 시도 

src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.style.ts, src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.tsx, src/core/mockupData.ts
- close #167 
- 외부 새 창 열기 위해서 `window.open(item.url)` 썼습니당
=> [토너먼트] outlink 보러가기 기능 구현 및 스타일 수정

src/pages/Start/StartHeader/StartHeader.style.ts, src/pages/Start/StartHeader/StartHeader.tsx
=> [메인] 햄버거 메뉴 헤더 구현 

src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx, src/hooks/queries/tournament/useGetRanking.tsx
=> [토너먼트] api access token 없이

src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx, src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx, src/utils/shareKakaoLink.ts
=> [카카오 공유하기] url 설정

src/components/TournamentNew/Intro/TournamentContainer.tsx
=> [토너먼트] 라우터 파람값에 의한 수정 

src/components/TournamentNew/Intro/TournamentContainer.tsx, src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.tsx
=> [토너먼트] 토너먼트 플로우 라우터 수정

src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx
=> [선물페이지] 선물 에서 토너먼트 라우터 수정

src/components/OnBoardingSteps/Step05/Step05.tsx, src/components/OnBoardingSteps/Step06/Step06.tsx, src/hooks/queries/onboarding/useKakaoShare.tsx, src/pages/OnBoardingPage.tsx
=> [온보딩] 지웠던 POST 및 카카오 공유 & 입장 클릭 시 roomId 받아서 navigate 이동

src/components/TournamentNew/Intro/TournamentContainer.tsx, src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx, src/components/TournamentNew/TournamentResult/TournamentResult.tsx, src/pages/TournamentOngoing.tsx
=> [토너먼트] get user roomid 프롭 전달

src/components/OnBoardingSteps/Step01/Step01.style.ts, src/components/OnBoardingSteps/Step01/Step01.tsx, src/components/OnBoardingSteps/Step02/Step02.tsx, src/components/OnBoardingSteps/Step03/Step03.style.ts, src/components/OnBoardingSteps/Step03/Step03.tsx, src/components/OnBoardingSteps/Step06/Step06.tsx, src/components/OnBoardingSteps/onboardingHeader/OnBoardingHeader.tsx, src/pages/Participants/ ParticipantsView.tsx
=> 초대 &  카카오공유 & 2차 qa

src/assets/svg/IcSettings.tsx, src/components/CardRoom/CardRoom.style.ts, src/components/CardRoom/EditCardRoom.tsx, src/components/CardRoom/ProgressCardRoom.tsx, src/components/Footer/Footer.style.ts, src/components/Footer/Footer.tsx, src/components/IcTag/Type1/Type1.style.ts, src/components/IcTag/Type2/Type2.style.ts, src/components/IcTag/Type3/Type3.style.ts, src/components/ScrollAnimationContainer/ScrollAnimation.style.ts, src/pages/Loading/Loading.tsx, src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts, src/pages/MyPage/Detail/DetailHeader/DetailHeader.style.ts, src/pages/MyPage/Detail/DetailHeader/DetailHeader.tsx, src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts, src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.tsx, src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.style.ts, src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.tsx, src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx, src/pages/MyPage/MyPage.style.ts, src/pages/MyPage/MyPage.tsx, src/pages/MyPage/MyPageHeader/MyPageHeader.style.ts, src/pages/Start/Start.style.ts, src/pages/Start/Start.tsx, src/pages/Start/StartHeader/StartHeader.style.ts
- close #259
- Home/Mypage 디자인 qa 진행 완료
=> Home/Mypage 디자인 qa 진행 완료

src/components/TournamentNew/Intro/TournamentContainer.tsx, src/components/TournamentNew/TournamentResult/TournamentResultUser/TournamentResultUser.tsx, src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx, src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx, src/router/Router.tsx, src/types/tournament/index.d.ts
=> [토너먼트] gifted 속성 받아오기 

src/components/OnBoardingSteps/Step06/OnboardingFinalHeader.tsx, src/components/OnBoardingSteps/Step06/Step06.style.ts, src/pages/OnBoardingPage.tsx, src/pages/Start/Start.tsx
=> [온보딩] 온보딩 파이널 뷰 스타일 수정

src/apis/client.ts, src/components/Login/index.tsx
- close #313 
- [리프레쉬 토큰] 확인을 위한 console.log 작성
=> [리프레쉬 토큰] 확인을 위한 console.log 작성

src/apis/client.ts, src/components/Login/index.tsx
- close #313 
- response data 형식을 data. 추가해서 변경했다. console.log 찍어봤더니 그 부분이 실행이 안되고 있어서. message인식을 못하고 있다고 판단했기 때문이다.
=> [리프레쉬 토큰] reponse data 형식 변경

src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx
=> [마이페이지] 라우터 giftee -> gifteeName변경

src/pages/Participants/ParticipantsView.tsx
=> isToken 기본 값 언디파인드로 변경

src/pages/Participants/ParticipantsView.tsx
=> [온보딩] useEffect 안 조건문 제거(02:36)

src/components/GiftAdd/AddGiftFooter/AddGiftFooter.styled.ts, src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.styled.ts, src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx, src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WithoutLinkWriteItemInfo.tsx, src/components/GiftAdd/AddGiftLink/common/GiftAddNextBtn/GiftAddNextBtn.styled.ts, src/components/GiftAdd/AddGiftLink/common/InputUrl/InputUrl.styled.ts, src/components/GiftAdd/AddGiftLink/common/InputUrl/InputUrl.tsx, src/components/GiftAdd/ItemTextField/ItemTextField.styled.ts, src/components/GiftAdd/ItemTextField/ItemTextField.tsx, src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx, src/components/common/MiniTimer/MiniTimer.styled.ts, src/components/common/MiniTimer/MiniTimer.tsx
- close #402 
- 간단한 스타일 수정입니다!
- 시계 아이콘 수정 및 링크 텍스트 색상 수정, 버튼 수정 가능한 화면입니다.
(실제 화면에서는 포커싱 될 때 핑크색으로 잘 뜨는데 녹화본은 색깔이 좀 다르네요?! 실제로는 잘 됩니다!)
https://github.com/SWEET-DEVELOPERS/sweet-client/assets/92876819/72be1d2b-95e3-4c89-a0fc-8326f14d164f
- 이미지 잘리지 않게 수정
=> [1.5차] 선물등록 스타일 QA

src/components/OnBoardingSteps/Step06/Step06.tsx, src/pages/Participants/ParticipantsView.tsx
=> [온보딩]16시 54분 기준 카카오 로그인 강제로 보이게 하여 svg의 문제인지 확인하는 작업

src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
=> [선물방 메인] 올바른 url로 복사를 위한 env 파일 변경 및 '/'추가

src/components/OnBoardingSteps/Step06/OnboardingFinalFooter.tsx, src/pages/Participants/ParticipantsView.tsx
- close #427 
일부 수정한 부분이라 가볍게 확인해주셔도 될 것 같습니다~
=> [온보딩]입장하기 버튼 클릭 시 아무 작동 없던 문제 해결

src/components/Tournament/TournamentFlow/TournamentFlowContainer.tsx, src/components/Tournament/TournamentFlow/TournamentFlowLogic.tsx
=> [토너먼트] 분리 로직 롤백 hotfix

src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx, src/components/GiftHome/common/GiftHomeShowcaseItem.styled.ts
- close #455 
- 누락된 부분 추가한 간단한 PR입니다!
=> [선물 등록] 링크 입력 이름 추가

package.json, yarn.lock
- close #461 
- 이미지 압축 라이브러리와 스켈레톤 UI 라이브러리 설치했으니 확인해주세요~!
=> [공통] 이미지 최적화 라이브러리 설치

index.html
- close #514 
- 저희 sweet 이메일 계정 확인이 어려워, 일단 제 계정으로 해놨습니다 ! 계정 생성이 어렵지 않아, 스윗 이메일에도 적용해도 될 거 같아요 : ) 간단해서 approve 해주시면 merge 시키고, 추후 더 구체적인 ga 를 위해 리펙토링 하면 될 거같습니다!
=> 해당 부분 전달 받은 계정 id 로 수정했습니다 !
=> [유저 트래픽] vercel analytics -> google analytics migration
